name: 'Update Tags Action'
description: 'Update Tags on Release for Semantic Versions'
author: 'Shane'
branding:
    icon: 'tag'
    color: 'red'

inputs:
    major:
        description: 'Update Major Tag'
        required: false
        default: 'true'
    minor:
        description: 'Update Minor Tag'
        required: false
        default: 'true'

runs:
    using: 'node20'
    main: 'dist/index.js'
